# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('臺灣言語資料庫', '0003_auto_20151009_0731_版權加長度'),
    ]

    operations = [
        migrations.AddField(
            model_name='文本表',
            name='音標資料',
            field=models.TextField(blank=True, default=''),
        ),
    ]
