# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('臺灣言語資料庫', '0004_文本表_音標資料'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='影音表',
            name='網頁影音資料',
        ),
        migrations.RenameField(
            model_name='影音表',
            old_name='原始影音資料',
            new_name='影音資料',
        ),
    ]
