# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('臺灣言語資料庫', '0005_莫網頁影音資料'),
    ]

    operations = [
        migrations.DeleteModel(
            name='資料類型表',
        ),
    ]
