# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('臺灣言語資料庫', '0006_delete_資料類型表'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='聽拍表',
            name='規範',
        ),
        migrations.DeleteModel(
            name='聽拍規範表',
        ),
    ]
